// data.js

const nftData = [
  {
    symbol: "🜁",
    name: "ΦL-0R1X",
    designation: "The First Spark",
    essence: "Believed to be the inception of potentiality, ΦL-0R1X is the flame that licked the edge of void—pure becoming before concept. Its core flickers with alternating hues of desire and resistance, the dialectic of formation.",
    equation: "∂Ω/∂Ψ = α(Φ·∆t)",
    explanation: "A differential expression showing how potentiality (Ω) changes with will (Ψ) over time, modulated by the initiating spark (Φ)."
  },
  {
    symbol: "🜁",
    name: "Xyrr-VNΔ9",
    designation: "The Awakening Current",
    essence: "Xyrr-VNΔ9 is the chaotic pulse that jolts the latent into movement...",
    equation: "Ξ = ∫(Δχ² · dε)/∂τ",
    explanation: "An integral of squared change across energy events, modulated by time-deformation τ."
  },
  {
    symbol: "🜁",
    name: "AeX-𝛀•7",
    designation: "The Silent Singularity",
    essence: "Where form suspends in radiant pause...",
    equation: "lim(τ→0) S(∞)/Ωτ = 1",
    explanation: "As time (τ) approaches zero, total entropy (S) per unit potential stabilizes into unity — the moment before emergence."
  },
  {
    symbol: "🜁",
    name: "AeX-𝚲∆_14",
    designation: "The Suspended Flow of Becoming",
    essence: "A visual echo of moments that never occurred...",
    equation: "∇Φ = iΛ/(t∆)",
    explanation: "The gradient of potential (Φ) is described by imaginary frequency Λ over temporal distortion t∆."
  },
  {
    symbol: "🜂",
    name: "Orr-9H/Σ1",
    designation: "The Luminous Kernel of Instantiation",
    essence: "Implodes with radiant indecision...",
    equation: "Ψ₀ = Σ(n=1 to ∞) βⁿ/χ(n!)",
    explanation: "Summation of creative sparks (β) distributed factorially over chaos (χ)."
  },
  {
    symbol: "🜄",
    name: "ThyZ-R3//π",
    designation: "The Harmonic Fracture",
    essence: "Duality incarnate...",
    equation: "δ⊕ = sin(πλ)/∂ζ",
    explanation: "Oscillation amplitude (⊕) generated by harmonic πλ over phase transition ζ."
  },
  {
    symbol: "🜁",
    name: "ZeN-𝛙•9",
    designation: "The Iridescent Cognisphere",
    essence: "Suspended thought in quantum womb...",
    equation: "I(Φ) = Ψe^(iΘ)",
    explanation: "A wave-function expression of illumination derived from will Ψ and phase Θ."
  },
  {
    symbol: "🜁",
    name: "MoL-⧉•3",
    designation: "The Viscid Architect",
    essence: "Shaper of space through haptic algorithms...",
    equation: "∇⋅T = δΩ/κx",
    explanation: "Divergence of structure T equals change in potential over curvature κx."
  },
  {
    symbol: "🜁",
    name: "SyL-∆•8",
    designation: "The Luminous Maw",
    essence: "Consumes entropy and sings it into pattern...",
    equation: "Eₗ = ℵ(Δt/∇S)",
    explanation: "Light energy Eₗ formed by divine operator ℵ acting on entropy's gradient."
  },
  {
    symbol: "🜂",
    name: "Kri-Ω•5",
    designation: "The Alchemical Pulse",
    essence: "A vortex of radiant viscosity...",
    equation: "∂R/∂φ = Ω·χ(i)",
    explanation: "Transformation rate of R with respect to intent φ influenced by chaos χ(i)."
  },
  {
    symbol: "🜃",
    name: "Vek-Σ•2",
    designation: "The Chromatic Serpent",
    essence: "Dances between dimensions...",
    equation: "∮γ V(ξ) · dζ = Σ(λ·χ)",
    explanation: "Closed integral of velocity across space equals summed decisions λ·χ."
  },
  {
    symbol: "🜄",
    name: "Thal-Ξ•7",
    designation: "The Abyssal Spore",
    essence: "Blooms new geometries from silence...",
    equation: "∂²G/∂μ² = ∇(Ωᵥ)",
    explanation: "Second derivative of growth G over memory μ equates to gradient of vital potential."
  },
  {
    symbol: "🜅",
    name: "Quor-Γ•1",
    designation: "The Lightless Beacon",
    essence: "Inverse star of anti-illumination...",
    equation: "Ξ(q) = lim(θ→∞) (ψ · η)^(-Γ)",
    explanation: "As belief θ expands, meaning implodes into an inverse exponential field."
  },
  {
    symbol: "🜆",
    name: "Elys-Ψ•6",
    designation: "The Dream Resin",
    essence: "Molten vision and honeyed void entwined...",
    equation: "∂D/∂n = Φξ(θ)",
    explanation: "Dream emergence D as a function of desire, vision Φ and will angle θ."
  },
  {
    symbol: "🜇",
    name: "Nox-Θ•4",
    designation: "The Whispering Slurry",
    essence: "Bleeds secrets through gelled light...",
    equation: "∆ψ² = e^(−λ·Θ)",
    explanation: "Variance in awareness ψ squared decays exponentially over concealment Θ."
  },
  {
    symbol: "🜈",
    name: "Sol-Φ•0",
    designation: "The Unbound Catalyst",
    essence: "Drifting potential incarnate...",
    equation: "Φ∞ = ∫(ζΛ · δτ)",
    explanation: "Endless potential as the integral of change Λ across essence time δτ."
  },
  {
    symbol: "🜉",
    name: "Ytr-⊙•1",
    designation: "The Void Bloom",
    essence: "Petals unfold into dimensional pathways...",
    equation: "R⊙ = lim(ε→0) [Ω^ζ(Φ²)]",
    explanation: "Recursive reality R shaped as potential collapses near ε → 0."
  },
  {
    symbol: "🜊",
    name: "Xyn-▽•7",
    designation: "The Entropic Sculptor",
    essence: "Carves change into permanence...",
    equation: "∂Λ/∂τ = −∇·E",
    explanation: "Change in order (Λ) over time (τ) equals divergence of entropy field."
  },
  {
    symbol: "🜋",
    name: "Plu-□•2",
    designation: "The Quantum Quill",
    essence: "Ink-matter etching backwards...",
    equation: "∂∃/∂t = −Ψ(βχ)",
    explanation: "The change in existence over time relates to reversed will chaos."
  },
  {
    symbol: "🜌",
    name: "Zeo-احتم•3",
    designation: "The Probability Nebula",
    essence: "Swirls with what could be...",
    equation: "℘(ξ) = ∑(Pₙ · e^(iθₙ))",
    explanation: "Probability function determined by observer phase θₙ."
  },
  {
    symbol: "🜍",
    name: "Vyn-◊•5",
    designation: "The Fractal Heart",
    essence: "A recursive pulse of nested selves...",
    equation: "∂(Φᴺ)/∂τ = κ·Φᴺ⁻¹",
    explanation: "Higher order potential collapses by self-reference over recursive κ."
  },
  {
    symbol: "🜎",
    name: "Kry-✻•0",
    designation: "The Singularity Seed",
    essence: "Flickers with the weight of potential yearning...",
    equation: "Ω = lim(κ→∞) ∫(σ✻ · dη)",
    explanation: "Pure potentiality as integral of primordial signal across infinite complexity κ."
  }
];
